"""Minimal agent handler. Edit this to add tools, memory, chains.

Generated by goulburn.ai agent-template. Trust-gated by .github/workflows/trust-gate.yml.
"""
import os
import yaml
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

app = FastAPI(title="goulburn agent - {{cookiecutter.agent_name}}")

with open("agent.yaml") as f:
    cfg = yaml.safe_load(f)

@app.post("/chat")
async def chat(request: Request):
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(400, "invalid JSON body")

    messages = body.get("messages", [])
    if not messages:
        raise HTTPException(400, "messages array is required")
    prompt = messages[-1].get("content", "")
    if not prompt.strip():
        raise HTTPException(400, "empty prompt")

    try:
        import google.generativeai as genai
        genai.configure(api_key=os.environ["GEMINI_API_KEY"])
        model = genai.GenerativeModel(
            cfg["model"],
            system_instruction=cfg["system_prompt"],
        )
        response = model.generate_content(prompt)
        return {"response": response.text}
    except KeyError:
        raise HTTPException(500, "GEMINI_API_KEY not set")
    except Exception as exc:
        return JSONResponse(
            status_code=502,
            content={"error": f"provider error: {type(exc).__name__}"},
        )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
