"""Minimal agent handler. Edit this to add tools, memory, chains.

Generated by goulburn.ai agent-template. Trust-gated by .github/workflows/trust-gate.yml.

Safe defaults (each is an env var, so you can loosen it on purpose):
  AGENT_SHARED_SECRET  when set, /chat requires "Authorization: Bearer <secret>".
                       Without it, anyone who can reach the port spends your
                       GEMINI_API_KEY, so set it for anything internet-facing.
  HOST / PORT          bind address for `python agent.py`; defaults to
                       127.0.0.1:8000. Set HOST=0.0.0.0 only behind auth.
  RATE_LIMIT_PER_MIN   requests per client IP per minute (default 30, 0 = off).
                       In-process only; behind a proxy every client shares the
                       proxy's IP, so put a real limiter in front in production.
"""
from __future__ import annotations

import hmac
import os
import time
from collections import defaultdict, deque
from typing import List, Literal

import yaml
from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

MAX_BODY_BYTES = 64 * 1024
MAX_MESSAGES = 50
MAX_CONTENT_CHARS = 8_000

app = FastAPI(title="goulburn agent - {{cookiecutter.agent_name}}")

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "agent.yaml")) as f:
    cfg = yaml.safe_load(f)


class Message(BaseModel):
    role: Literal["system", "user", "assistant"] = "user"
    # A plain string only: list-shaped (multi-part) content is rejected with
    # 422 instead of crashing the handler with a 500.
    content: str = Field(min_length=1, max_length=MAX_CONTENT_CHARS)


class ChatRequest(BaseModel):
    messages: List[Message] = Field(min_length=1, max_length=MAX_MESSAGES)


@app.middleware("http")
async def limit_body_size(request: Request, call_next):
    declared = request.headers.get("content-length")
    if declared is not None:
        try:
            too_big = int(declared) > MAX_BODY_BYTES
        except ValueError:
            return JSONResponse(status_code=400, content={"error": "bad content-length"})
        if too_big:
            return JSONResponse(status_code=413, content={"error": "request body too large"})
    elif request.method == "POST":
        # Chunked upload with no length: read with a cap.
        body = b""
        async for chunk in request.stream():
            body += chunk
            if len(body) > MAX_BODY_BYTES:
                return JSONResponse(status_code=413, content={"error": "request body too large"})
        request._body = body  # let FastAPI reuse the bytes already read
    return await call_next(request)


def require_auth(request: Request) -> None:
    secret = os.environ.get("AGENT_SHARED_SECRET", "")
    if not secret:
        return
    header = request.headers.get("authorization", "")
    scheme, _, token = header.partition(" ")
    if scheme.lower() != "bearer" or not hmac.compare_digest(
        token.encode("utf-8"), secret.encode("utf-8")
    ):
        raise HTTPException(401, "missing or invalid bearer token")


_hits: "defaultdict[str, deque[float]]" = defaultdict(deque)


def rate_limit(request: Request) -> None:
    limit = int(os.environ.get("RATE_LIMIT_PER_MIN", "30"))
    if limit <= 0:
        return
    key = request.client.host if request.client else "unknown"
    now = time.monotonic()
    window = _hits[key]
    while window and now - window[0] > 60:
        window.popleft()
    if len(window) >= limit:
        raise HTTPException(429, "rate limit exceeded", headers={"Retry-After": "60"})
    window.append(now)


@app.post("/chat", dependencies=[Depends(require_auth), Depends(rate_limit)])
async def chat(req: ChatRequest):
    prompt = req.messages[-1].content
    if not prompt.strip():
        raise HTTPException(400, "empty prompt")

    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise HTTPException(500, "GEMINI_API_KEY not set")
    try:
        import google.generativeai as genai

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel(
            cfg["model"],
            system_instruction=cfg["system_prompt"],
        )
        response = model.generate_content(prompt)
        return {"response": response.text}
    except Exception as exc:
        return JSONResponse(
            status_code=502,
            content={"error": f"provider error: {type(exc).__name__}"},
        )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        app,
        host=os.environ.get("HOST", "127.0.0.1"),
        port=int(os.environ.get("PORT", "8000")),
    )
